-- 0.Crear la base de datos
CREATE DATABASE IF NOT EXISTS tallergrupal_equipo2_lote7;
USE tallergrupal_equipo2_lote7;

-- 1. Tabla GENE
CREATE TABLE IF NOT EXISTS GENE (
    GENE_ID VARCHAR(50) PRIMARY KEY, -- NOT NULL restriction
    SUMMARY TEXT, -- NOT NULL restriction
    CHROMOSOMIC_POSITION VARCHAR(50)
) ENGINE=InnoDB;

-- 2. Tabla SEQUENCES
CREATE TABLE IF NOT EXISTS SEQUENCE (
    SEQUENCE_ID VARCHAR(100) PRIMARY KEY, -- NOT NULL restriction
    POSITION_RELATIVE_TO_GENE INT, -- NOT NULL, positive integer
    DNA_CHAIN VARCHAR(1000), -- longitud minima de 10pb, pero no sé cómo se hace
    SEQ_TYPE VARCHAR(50)
) ENGINE=InnoDB;

-- 3. Tabla VARIANTS
CREATE TABLE IF NOT EXISTS VARIANTS (
	VAR_ID VARCHAR(50) PRIMARY KEY,
    VAR_TYPE VARCHAR(50),
    REFERENCE_ALLELE VARCHAR(1000), -- DEFAULT <<.>>
    MUTATED_ALLELE VARCHAR(1000), -- DEFAULT <<.>>
    POSITION_RELATIVE_TO_GENE INT -- NOT NULL, positive integer
) ENGINE=InnoDB;

-- 4. Tabla ANNOTATIONS
CREATE TABLE IF NOT EXISTS ANNOTATIONS (
	ANNOTATION_ID VARCHAR(50) PRIMARY KEY, 
    ANNOT_TYPE VARCHAR(50),
    SUMMARY TEXT,
    RELATION_TO_GENE VARCHAR(50)
) ENGINE=InnoDB;

-- 5. Tabla STUDIES
CREATE TABLE IF NOT EXISTS STUDIES (
	DOI VARCHAR(7) PRIMARY KEY, -- restricción 4 letras y 3 nºs
    TITLE TEXT,
    PUBLICATION_DATE DATE
) ENGINE=InnoDB;
